# -*- coding: utf-8 -*-
{
    'name': 'Hospital Management',
    'version': '12.0.1.0.0',
    'category': 'Learning odoo',
    'summary': 'Module for managing the Hospitals',
    'sequence': 1,
    'description': """App quản lý bệnh viên""",
    'author': 'Binh Nguyen Cong',
    'website': 'https://www.odoo.com/page/hospital-patient',
    'depends': ['mail', 'sale', 'report_xlsx', 'board', 'web_timeline', 'web_notify', 'website', 'point_of_sale'],
    'data': [
        # 'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/data.xml',
        'data/cron.xml',
        'wizards/create_appointment.xml',
        'views/patient.xml',
        'views/appointment.xml',
        'views/doctor.xml',
        'views/lab.xml',
        'views/sale_order.xml',
        'views/patient_view.xml',
        'views/template.xml',
        'views/settings.xml',
        'views/dashboard.xml',
        'reports/patient_card.xml',
        'reports/report.xml',
        'reports/sale_report_inherit.xml',
        'reports/appointment.xml',
        'views/server_action.xml',
        'data/mail_template.xml',
        'views/website_form.xml',
        'views/pos_sale.xml',
    ],
    'demo': [],
    'images': ['static/description/icon.png'],
    'installable': True,
    'application': True,
    'auto_install': False,
}
